name = "my-worker"
main = "api/index.js"
compatibility_date = "2024-11-20"  # Update to the current date

[env.production]
account_id = "your-cloudflare-account-id"
route = ""  # Optional: Add your custom domain or leave blank for workers.dev
